site_name: Sample site
theme:
  name: material
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.expand
      - navigation.top
      - content.code.copy
  language: ja
  icon:
    logo: simple/gitbook
    favicon: simple/gitbook
docs_dir: docs
use_directory_urls: false
nav:
  - Introduction: index.md
  - Sample:
      - template: template.md
markdown_extensions:
  - tables
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      linenums: true
      noclasses: true
      pygments_style: xcode
      use_pygments: true