site_name: Sample site
theme:
  name: material
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.expand
      - navigation.top
      - content.code.copy
      - toc.integrate
      - navigation.indexes
  language: ja
  icon:
    logo: simple/gitbook
    favicon: simple/gitbook
docs_dir: docs
extra_css:
  - extra.css
use_directory_urls: false
nav:
- index.md
- sample:
  - template: template.md
  - mermaid: mermaid.md
markdown_extensions:
  - tables
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      linenums: true
      noclasses: true
      pygments_style: xcode
      use_pygments: true
  - toc:
      toc_depth: 2